<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Repository\Traits\ExportTrait;

/**
 * CostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostRepository extends \Doctrine\ORM\EntityRepository
{
    use ExportTrait;
    public function getCostsForLastMonth(User $user)
    {
        $qb = $this->createQueryBuilder("entity");
        return $this->getData($user, $qb);
    }
}
