<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * RevenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevenueRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteByUser(User $user)
    {
        $qb = $this->createQueryBuilder("entity");
        $result = $qb->delete('AppBundle:Revenue',"entity")
            ->where($qb->expr()->eq('entity.user', $user->getId()))
            ->getQuery()
            ->getResult();
    }

    public function updateIsArcievedByUser(User $user)
    {
        $qb = $this->createQueryBuilder("entity");
        $result = $qb->update('AppBundle:Revenue',"entity")
            ->where($qb->expr()->eq('entity.user', $user->getId()))
            ->andWhere($qb->expr()->eq('entity.isArchieved', 0))
            ->set('entity.isArchieved', true)
            ->getQuery()
            ->getResult();
    }
}
